In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [17]:
path_file = r'C:\Users\ASUS\Desktop\insurance-churn-analysis\data\insurance_policyholder_churn_synthetic.csv'

df = pd.read_csv(path_file)

In [34]:
df.shape

(50000, 39)

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 39 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   customer_id                  50000 non-null  int64
 1   as_of_date                   50000 non-null  object
 2   region_name                  50000 non-null  object
 3   age                          50000 non-null  int64
 4   age_band                     50000 non-null  object
 5   marital_status               50000 non-null  object
 6   customer_tenure_months       50000 non-null  int64
 7   multi_policy_flag            50000 non-null  int64
 8   num_policies                 50000 non-null  int64
 9   policy_type                  50000 non-null  object
 10  renewal_month                50000 non-null  int64
 11  current_premium              50000 non-null  float64
 12  premium_last_year            50000 non-null  float64
 13  premium_change_pct           50000 non-null  float64
 14  num_price_increases_last_3y  50000 non-null  int64
 15  coverage_amount              50000 non-null  float64
 16  premium_to_coverage_ratio    50000 non-null  float64
 17  payment_frequency            50000 non-null  object
 18  autopay_enabled              50000 non-null  int64
 19  late_payment_count_12m       50000 non-null  int64
 20  missed_payment_flag          50000 non-null  int64
 21  payment_method_change_flag   50000 non-null  int64
 22  num_claims_12m               50000 non-null  int64
 23  num_approved_claims_12m      50000 non-null  int64
 24  num_rejected_claims_12m      50000 non-null  int64
 25  num_pending_claims_12m       50000 non-null  int64
 26  avg_claim_amount             50000 non-null  float64
 27  total_claim_amount_12m       50000 non-null  float64
 28  total_payout_amount_12m      50000 non-null  float64
 29  payout_ratio_12m             50000 non-null  float64
 30  avg_settlement_time_days     50000 non-null  int64
 31  days_since_last_claim        50000 non-null  int64
 32  num_contacts_12m             50000 non-null  int64
 33  complaint_flag               50000 non-null  int64
 34  complaint_resolution_days    50000 non-null  int64
 35  quote_requested_flag         50000 non-null  int64
 36  coverage_downgrade_flag      50000 non-null  int64
 37  churn_flag                   50000 non-null  int64
 38  churn_type                   50000 non-null  object
dtypes: float64(9), int64(23), object(7)
memory usage: 14.9+ MB

In [38]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
customer_id,50000.0,25000.500000,14433.901067,1.000000,12500.750000,25000.500000,37500.250000,50000.000000
age,50000.0,51.461700,19.644405,18.000000,34.000000,52.000000,68.000000,85.000000
customer_tenure_months,50000.0,90.368820,51.835180,1.000000,45.000000,90.000000,135.000000,180.000000
multi_policy_flag,50000.0,0.318640,0.465954,0.000000,0.000000,0.000000,1.000000,1.000000
num_policies,50000.0,1.638760,1.041848,1.000000,1.000000,1.000000,2.000000,4.000000
renewal_month,50000.0,6.497620,3.435030,1.000000,4.000000,6.000000,9.000000,12.000000
current_premium,50000.0,1047.882399,455.932852,120.000000,745.707500,1009.755000,1324.462500,3348.350000
premium_last_year,50000.0,994.319903,440.611049,92.740000,701.577500,954.720000,1259.262500,3374.460000
premium_change_pct,50000.0,0.060795,0.080826,-0.160200,0.004600,0.059800,0.116300,0.410500
num_price_increases_last_3y,50000.0,1.669360,0.818957,0.000000,1.000000,2.000000,2.000000,3.000000
coverage_amount,50000.0,202144.417452,194591.499941,2000.000000,26633.240000,143523.870000,361905.910000,922303.730000
premium_to_coverage_ratio,50000.0,0.021738,0.041392,0.000154,0.002624,0.009865,0.031266,1.087921
autopay_enabled,50000.0,0.650400,0.476848,0.000000,0.000000,1.000000,1.000000,1.000000
late_payment_count_12m,50000.0,0.500940,0.784533,0.000000,0.000000,0.000000,1.000000,8.000000
missed_payment_flag,50000.0,0.006260,0.078873,0.000000,0.000000,0.000000,0.000000,1.000000
payment_method_change_flag,50000.0,0.140580,0.347591,0.000000,0.000000,0.000000,0.000000,1.000000
num_claims_12m,50000.0,0.145260,0.385749,0.000000,0.000000,0.000000,0.000000,4.000000
num_approved_claims_12m,50000.0,0.126980,0.353580,0.000000,0.000000,0.000000,0.000000,3.000000
num_rejected_claims_12m,50000.0,0.010040,0.101683,0.000000,0.000000,0.000000,0.000000,2.000000
num_pending_claims_12m,50000.0,0.008240,0.091281,0.000000,0.000000,0.000000,0.000000,2.000000
avg_claim_amount,50000.0,7210.003828,7514.893803,330.230000,3008.020000,4954.870000,8556.975000,200000.000000
total_claim_amount_12m,50000.0,883.646577,3388.931068,0.000000,0.000000,0.000000,0.000000,199344.170000
total_payout_amount_12m,50000.0,671.667783,2603.038616,0.000000,0.000000,0.000000,0.000000,149508.130000
payout_ratio_12m,50000.0,0.774165,0.039917,0.550000,0.750000,0.750000,0.800000,0.850000
avg_settlement_time_days,50000.0,18.175720,7.949160,1.000000,13.000000,18.000000,24.000000,53.000000
days_since_last_claim,50000.0,971.374400,501.320714,1.000000,560.000000,981.000000,1402.000000,1824.000000
num_contacts_12m,50000.0,1.285900,1.156213,0.000000,0.000000,1.000000,2.000000,10.000000
complaint_flag,50000.0,0.040440,0.196991,0.000000,0.000000,0.000000,0.000000,1.000000
complaint_resolution_days,50000.0,0.493060,2.673779,0.000000,0.000000,0.000000,0.000000,31.000000
quote_requested_flag,50000.0,0.108480,0.310989,0.000000,0.000000,0.000000,0.000000,1.000000
coverage_downgrade_flag,50000.0,0.098520,0.298019,0.000000,0.000000,0.000000,0.000000,1.000000
churn_flag,50000.0,0.301660,0.458983,0.000000,0.000000,0.000000,1.000000,1.000000

In [ ]:
df.isna().value_counts()

The number of Null is: customer_id  as_of_date  region_name  age    age_band  marital_status  customer_tenure_months  multi_policy_flag  num_policies  policy_type  renewal_month  current_premium  premium_last_year  premium_change_pct  num_price_increases_last_3y  coverage_amount  premium_to_coverage_ratio  payment_frequency  autopay_enabled  late_payment_count_12m  missed_payment_flag  payment_method_change_flag  num_claims_12m  num_approved_claims_12m  num_rejected_claims_12m  num_pending_claims_12m  avg_claim_amount  total_claim_amount_12m  total_payout_amount_12m  payout_ratio_12m  avg_settlement_time_days  days_since_last_claim  num_contacts_12m  complaint_flag  complaint_resolution_days  quote_requested_flag  coverage_downgrade_flag  churn_flag  churn_type
False        False       False        False  False     False           False                   False              False         False        False          False            False              False               False                        False            False                      False              False            False                   False                False                       False           False                    False                    False                   False             False                   False                    False             False                     False                  False             False           False                      False                 False                    False       False         50000
Name: count, dtype: int64

In [ ]:
print("The number of duplicates are: ", df.duplicated().sum())

the number of duplicates are:  0

In [62]:
df.duplicated().sum()

np.int64(0)

In [68]:
df.head()

,customer_id,as_of_date,region_name,age,age_band,marital_status,customer_tenure_months,multi_policy_flag,num_policies,policy_type,...,payout_ratio_12m,avg_settlement_time_days,days_since_last_claim,num_contacts_12m,complaint_flag,complaint_resolution_days,quote_requested_flag,coverage_downgrade_flag,churn_flag,churn_type
0,1,2025-12-31,Manawatu-Whanganui,24,18-24,Married,128,1,4,Auto,...,0.75,7,1616,0,0,0,0,0,0,No churn
1,2,2025-12-31,Auckland,70,65-74,Married,76,1,3,Auto,...,0.75,15,1760,1,0,0,0,0,0,No churn
2,3,2025-12-31,Bay of Plenty,62,55-64,Married,129,0,1,Auto,...,0.75,24,1581,1,0,0,0,0,0,No churn
3,4,2025-12-31,Bay of Plenty,47,45-54,Single,104,0,1,Auto,...,0.75,17,1688,1,0,0,0,0,0,No churn
4,5,2025-12-31,Bay of Plenty,47,45-54,Married,22,1,3,Life,...,0.85,24,1592,1,0,0,0,0,0,No churn

In [79]:
# churn_flag,"Target label: 1 = churned at renewal, 0 = retained"
# Plot all columns to Churn flag to see if I can see any correlations or relations with all the features