In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
path_file = r'C:\Users\ASUS\Desktop\insurance-churn-analysis\data\insurance_policyholder_churn_synthetic.csv'

df = pd.read_csv(path_file)

In [4]:
df.shape

(50000, 40)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 40 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   customer_id                  50000 non-null  int64
 1   as_of_date                   50000 non-null  object
 2   region_name                  50000 non-null  object
 3   age                          50000 non-null  int64
 4   age_band                     50000 non-null  object
 5   marital_status               50000 non-null  object
 6   customer_tenure_months       50000 non-null  int64
 7   multi_policy_flag            50000 non-null  int64
 8   num_policies                 50000 non-null  int64
 9   policy_type                  50000 non-null  object
 10  renewal_month                50000 non-null  int64
 11  current_premium              50000 non-null  float64
 12  premium_last_year            50000 non-null  float64
 13  premium_change_pct           50000 non-null  float64
 14  num_price_increases_last_3y  50000 non-null  int64
 15  coverage_amount              50000 non-null  float64
 16  premium_to_coverage_ratio    50000 non-null  float64
 17  payment_frequency            50000 non-null  object
 18  autopay_enabled              50000 non-null  int64
 19  late_payment_count_12m       50000 non-null  int64
 20  missed_payment_flag          50000 non-null  int64
 21  payment_method_change_flag   50000 non-null  int64
 22  num_claims_12m               50000 non-null  int64
 23  num_approved_claims_12m      50000 non-null  int64
 24  num_rejected_claims_12m      50000 non-null  int64
 25  num_pending_claims_12m       50000 non-null  int64
 26  avg_claim_amount             50000 non-null  float64
 27  total_claim_amount_12m       50000 non-null  float64
 28  total_payout_amount_12m      50000 non-null  float64
 29  payout_ratio_12m             50000 non-null  float64
 30  avg_settlement_time_days     50000 non-null  int64
 31  days_since_last_claim        50000 non-null  int64
 32  num_contacts_12m             50000 non-null  int64
 33  complaint_flag               50000 non-null  int64
 34  complaint_resolution_days    50000 non-null  int64
 35  quote_requested_flag         50000 non-null  int64
 36  coverage_downgrade_flag      50000 non-null  int64
 37  churn_flag                   50000 non-null  int64
 38  churn_type                   50000 non-null  object
 39  churn_probability_true       50000 non-null  float64
dtypes: float64(10), int64(23), object(7)
memory usage: 15.3+ MB

In [9]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
customer_id,50000.0,25000.500000,14433.901067,1.000000,12500.750000,25000.500000,37500.250000,50000.000000
age,50000.0,51.461700,19.644405,18.000000,34.000000,52.000000,68.000000,85.000000
customer_tenure_months,50000.0,90.368820,51.835180,1.000000,45.000000,90.000000,135.000000,180.000000
multi_policy_flag,50000.0,0.318640,0.465954,0.000000,0.000000,0.000000,1.000000,1.000000
num_policies,50000.0,1.638760,1.041848,1.000000,1.000000,1.000000,2.000000,4.000000
renewal_month,50000.0,6.497620,3.435030,1.000000,4.000000,6.000000,9.000000,12.000000
current_premium,50000.0,1047.882399,455.932852,120.000000,745.707500,1009.755000,1324.462500,3348.350000
premium_last_year,50000.0,994.319903,440.611049,92.740000,701.577500,954.720000,1259.262500,3374.460000
premium_change_pct,50000.0,0.060795,0.080826,-0.160200,0.004600,0.059800,0.116300,0.410500
num_price_increases_last_3y,50000.0,1.669360,0.818957,0.000000,1.000000,2.000000,2.000000,3.000000
coverage_amount,50000.0,202144.417452,194591.499941,2000.000000,26633.240000,143523.870000,361905.910000,922303.730000
premium_to_coverage_ratio,50000.0,0.021738,0.041392,0.000154,0.002624,0.009865,0.031266,1.087921
autopay_enabled,50000.0,0.650400,0.476848,0.000000,0.000000,1.000000,1.000000,1.000000
late_payment_count_12m,50000.0,0.500940,0.784533,0.000000,0.000000,0.000000,1.000000,8.000000
missed_payment_flag,50000.0,0.006260,0.078873,0.000000,0.000000,0.000000,0.000000,1.000000
payment_method_change_flag,50000.0,0.140580,0.347591,0.000000,0.000000,0.000000,0.000000,1.000000
num_claims_12m,50000.0,0.145260,0.385749,0.000000,0.000000,0.000000,0.000000,4.000000
num_approved_claims_12m,50000.0,0.126980,0.353580,0.000000,0.000000,0.000000,0.000000,3.000000
num_rejected_claims_12m,50000.0,0.010040,0.101683,0.000000,0.000000,0.000000,0.000000,2.000000
num_pending_claims_12m,50000.0,0.008240,0.091281,0.000000,0.000000,0.000000,0.000000,2.000000
avg_claim_amount,50000.0,7210.003828,7514.893803,330.230000,3008.020000,4954.870000,8556.975000,200000.000000
total_claim_amount_12m,50000.0,883.646577,3388.931068,0.000000,0.000000,0.000000,0.000000,199344.170000
total_payout_amount_12m,50000.0,671.667783,2603.038616,0.000000,0.000000,0.000000,0.000000,149508.130000
payout_ratio_12m,50000.0,0.774165,0.039917,0.550000,0.750000,0.750000,0.800000,0.850000
avg_settlement_time_days,50000.0,18.175720,7.949160,1.000000,13.000000,18.000000,24.000000,53.000000
days_since_last_claim,50000.0,971.374400,501.320714,1.000000,560.000000,981.000000,1402.000000,1824.000000
num_contacts_12m,50000.0,1.285900,1.156213,0.000000,0.000000,1.000000,2.000000,10.000000
complaint_flag,50000.0,0.040440,0.196991,0.000000,0.000000,0.000000,0.000000,1.000000
complaint_resolution_days,50000.0,0.493060,2.673779,0.000000,0.000000,0.000000,0.000000,31.000000
quote_requested_flag,50000.0,0.108480,0.310989,0.000000,0.000000,0.000000,0.000000,1.000000
coverage_downgrade_flag,50000.0,0.098520,0.298019,0.000000,0.000000,0.000000,0.000000,1.000000
churn_flag,50000.0,0.301660,0.458983,0.000000,0.000000,0.000000,1.000000,1.000000
churn_probability_true,50000.0,0.303564,0.232942,0.018915,0.130210,0.242322,0.414728,1.000000

In [17]:
# churn_flag,"Target label: 1 = churned at renewal, 0 = retained"
df["churn_flag"].value_counts(normalize=True) * 100

churn_flag
0    69.834
1    30.166
Name: proportion, dtype: float64

In [20]:
df.head(10).T

,0,1,2,3,4,5,6,7,8,9
customer_id,1,2,3,4,5,6,7,8,9,10
as_of_date,2025-12-31,2025-12-31,2025-12-31,2025-12-31,2025-12-31,2025-12-31,2025-12-31,2025-12-31,2025-12-31,2025-12-31
region_name,Manawatu-Whanganui,Auckland,Bay of Plenty,Bay of Plenty,Bay of Plenty,Auckland,Waikato,Wellington,Canterbury,Auckland
age,24,70,62,47,47,76,23,65,31,24
age_band,18-24,65-74,55-64,45-54,45-54,75+,18-24,65-74,25-34,18-24
marital_status,Married,Married,Married,Single,Married,Married,Single,Married,Married,Married
customer_tenure_months,128,76,129,104,22,88,41,105,162,154
multi_policy_flag,1,1,0,0,1,0,0,0,0,0
num_policies,4,3,1,1,3,1,1,1,1,1
policy_type,Auto,Auto,Auto,Auto,Life,Home,Auto,Home,Health,Auto
renewal_month,8,3,5,2,11,7,7,11,3,3
current_premium,1013.47,1126.9,984.7,373.61,974.18,832.83,1391.68,562.53,1685.01,809.29
premium_last_year,1060.04,1052.27,874.29,331.99,991.82,815.33,1328.72,549.83,1487.13,773.16
premium_change_pct,-0.0365,0.0479,0.1184,0.1502,0.0161,0.0309,0.0342,-0.0057,0.1516,0.0419
num_price_increases_last_3y,1,2,1,2,1,2,3,1,2,3
coverage_amount,8924.09,43734.45,23152.37,31806.95,302831.02,443383.01,38737.36,367533.31,139393.87,15302.27
premium_to_coverage_ratio,0.113565,0.025767,0.042531,0.011746,0.003217,0.001878,0.035926,0.001531,0.012088,0.052887
payment_frequency,Monthly,Monthly,Annual,Monthly,Monthly,Annual,Monthly,Monthly,Monthly,Annual
autopay_enabled,1,1,0,1,1,0,0,0,0,1
late_payment_count_12m,0,0,0,2,0,0,0,1,1,0
missed_payment_flag,0,0,0,0,0,0,0,0,0,0
payment_method_change_flag,0,0,0,0,0,0,0,0,1,0
num_claims_12m,0,0,0,0,0,0,0,0,0,0
num_approved_claims_12m,0,0,0,0,0,0,0,0,0,0
num_rejected_claims_12m,0,0,0,0,0,0,0,0,0,0
num_pending_claims_12m,0,0,0,0,0,0,0,0,0,0
avg_claim_amount,5250.19,4141.41,1956.42,3204.54,52392.59,16476.9,889.11,19391.57,2659.93,4011.91
total_claim_amount_12m,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
total_payout_amount_12m,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
payout_ratio_12m,0.75,0.75,0.75,0.75,0.85,0.75,0.75,0.75,0.8,0.75
avg_settlement_time_days,7,15,24,17,24,21,12,32,23,13
days_since_last_claim,1616,1760,1581,1688,1592,1691,682,1616,1767,616
num_contacts_12m,0,1,1,1,1,0,1,2,1,0
complaint_flag,0,0,0,0,0,0,0,0,0,0
complaint_resolution_days,0,0,0,0,0,0,0,0,0,0
quote_requested_flag,0,0,0,0,0,0,1,0,1,0
coverage_downgrade_flag,0,0,0,0,0,0,0,0,1,0
churn_flag,0,0,0,0,0,0,1,0,1,0
churn_type,No churn,No churn,No churn,No churn,No churn,No churn,Other,No churn,Price,No churn
churn_probability_true,0.048626,0.067888,0.223765,0.602455,0.050723,0.16832,0.334373,0.245879,0.710503,0.164344

In [23]:
df.duplicated().sum()

np.int64(0)

In [29]:
df.isna().sum().sum()

np.int64(0)

What’s the overall churn rate? 30.166 %
Which columns have missing values? none 
Which column is churn_probability_true? Last one
Which columns do you expect to matter most for churn, and why?  

In %
Other       16.694
Price       11.338
Service      1.308
Claims       0.428
Payment      0.398

In [ ]:
# Why Churn 
(df["churn_type"].value_counts() * 100) / 50000

churn_type
No churn    69.834
Other       16.694
Price       11.338
Service      1.308
Claims       0.428
Payment      0.398
Name: count, dtype: float64